---
# SSH server and client config changes
- name: authentication | sshd_config
  copy:
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
    mode: 0640
    owner: root
    group: wheel
  notify: reload sshd
