---
- name: deploy loader.conf.local / newsyslog.conf / pf.conf / rc.local /
  copy:
    src: "{{ item }}"
    dest: "/etc/"
    mode: 0640
    owner: root
    group: wheel
  loop:
    - loader.conf.local
    - newsyslog.conf
    - pf.conf
    - rc.local

- name: update .cshrc for root user - to colorize custom prompt
  copy:
    src: .cshrc
    dest: "/root/.cshrc"
    mode: 0640
    owner: root
    group: wheel
